root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/api"
  bin = "./tmp/main.exe"
  include_ext = ["go", "sql"]
  include_file = [".env"]
  exclude_dir = ["tmp", "vendor"]
  delay = 500
  kill_delay = "1s"

[log]
  time = true

[misc]
  clean_on_exit = true