root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build ./..."
  entrypoint = ["go", "run", "./cmd/api"]
  include_ext = ["go", "sql"]
  include_file = [".env"]
  exclude_dir = ["tmp", "vendor"]
  delay = 500
  kill_delay = "1s"

[log]
  time = true